export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  rating: number;
  reviews: number;
  badge?: string;
  category: string;
  description: string;
  details: string[];
  inStock: boolean;
  weight: string;
}

// All images verified working Unsplash source — food/nuts/dried-fruit photography
export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Medjool Dates',
    price: 17.80,
    originalPrice: 22.00,
    image: 'https://images.unsplash.com/photo-1593904308074-e1a53c4385f9?w=600&q=80&auto=format&fit=crop',
    rating: 4.9,
    reviews: 312,
    badge: 'Best Seller',
    category: 'Dates',
    description: 'Premium jumbo Medjool dates — soft, caramel-rich and naturally sweet.',
    details: ['No added sugar', 'Hand-picked', 'Rich in fiber & potassium', 'Gluten-free'],
    inStock: true,
    weight: '500g',
  },
  {
    id: 'p2',
    name: 'Dried Cranberries',
    price: 14.50,
    originalPrice: 18.00,
    image: 'https://images.unsplash.com/photo-1601493700518-cca0e0918fd1?w=600&q=80&auto=format&fit=crop',
    rating: 4.7,
    reviews: 189,
    badge: 'New',
    category: 'Berries',
    description: 'Tangy-sweet dried cranberries — packed with antioxidants.',
    details: ['High in vitamin C', 'Antioxidant-rich', 'Non-GMO', 'No added preservatives'],
    inStock: true,
    weight: '300g',
  },
  {
    id: 'p3',
    name: 'Dried Apricots',
    price: 10.60,
    image: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=600&q=80&auto=format&fit=crop',
    rating: 4.5,
    reviews: 97,
    category: 'Fruits',
    description: 'Naturally sweet apricots — no added sugar or sulfites.',
    details: ['Sulfite-free', 'No preservatives', 'High in iron', 'Natural sweetness'],
    inStock: true,
    weight: '400g',
  },
  {
    id: 'p4',
    name: 'Whole Cashews',
    price: 8.30,
    image: 'https://images.unsplash.com/photo-1567892737950-30c4db37cd89?w=600&q=80&auto=format&fit=crop',
    rating: 4.6,
    reviews: 143,
    category: 'Nuts',
    description: 'Whole roasted cashews — lightly salted and perfectly crunchy.',
    details: ['Lightly salted', 'Whole kernels', 'Rich in zinc', 'Heart-healthy fats'],
    inStock: true,
    weight: '300g',
  },
  {
    id: 'p5',
    name: 'Walnut Halves',
    price: 14.90,
    image: 'https://images.unsplash.com/photo-1604497181015-76590d828b75?w=600&q=80&auto=format&fit=crop',
    rating: 4.8,
    reviews: 256,
    badge: 'Popular',
    category: 'Nuts',
    description: 'Premium walnut halves — raw, unprocessed and omega-3 rich.',
    details: ['Omega-3 fatty acids', 'Raw & unprocessed', 'Brain health', 'High protein'],
    inStock: true,
    weight: '400g',
  },
  {
    id: 'p6',
    name: 'Dried Figs',
    price: 12.40,
    image: 'https://images.unsplash.com/photo-1601004890657-3ef98f68fec0?w=600&q=80&auto=format&fit=crop',
    rating: 4.6,
    reviews: 178,
    category: 'Fruits',
    description: 'Chewy dried figs, naturally dried and fiber-packed.',
    details: ['High in fiber', 'Natural calcium', 'No preservatives', 'Sweet & chewy'],
    inStock: true,
    weight: '350g',
  },
  {
    id: 'p7',
    name: 'Dried Blueberries',
    price: 19.90,
    originalPrice: 24.00,
    image: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=600&q=80&auto=format&fit=crop',
    rating: 4.9,
    reviews: 421,
    badge: 'Premium',
    category: 'Berries',
    description: 'Freeze-dried wild blueberries — antioxidant powerhouse.',
    details: ['Freeze-dried', 'Wild harvested', 'Rich in anthocyanins', 'Low calorie'],
    inStock: true,
    weight: '200g',
  },
  {
    id: 'p8',
    name: 'Raw Almonds',
    price: 16.50,
    image: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&q=80&auto=format&fit=crop',
    rating: 4.7,
    reviews: 203,
    category: 'Nuts',
    description: 'Raw almonds — skin-on, nutrient-dense and versatile.',
    details: ['Skin-on', 'Raw & natural', 'High in vitamin E', 'Protein-rich'],
    inStock: true,
    weight: '500g',
  },
  {
    id: 'p9',
    name: 'Pistachios',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1606923829579-0cb981a83e2e?w=600&q=80&auto=format&fit=crop',
    rating: 4.8,
    reviews: 167,
    badge: 'Premium',
    category: 'Nuts',
    description: 'Roasted in-shell pistachios — naturally salted, deliciously crunchy.',
    details: ['In-shell roasted', 'Naturally salted', 'High protein', 'Heart-healthy'],
    inStock: true,
    weight: '350g',
  },
  {
    id: 'p10',
    name: 'Dried Mango Slices',
    price: 13.20,
    image: 'https://images.unsplash.com/photo-1605027990121-cbae9e0642df?w=600&q=80&auto=format&fit=crop',
    rating: 4.6,
    reviews: 134,
    category: 'Fruits',
    description: 'Naturally sweet dried mango slices — tropical and chewy.',
    details: ['No added sugar', 'Tropical sourced', 'Rich in vitamin A', 'Chewy texture'],
    inStock: true,
    weight: '300g',
  },
  {
    id: 'p11',
    name: 'Golden Raisins',
    price: 9.80,
    image: 'https://images.unsplash.com/photo-1596591868231-05e892f9bee3?w=600&q=80&auto=format&fit=crop',
    rating: 4.4,
    reviews: 88,
    category: 'Fruits',
    description: 'Sun-dried golden raisins — naturally sweet and chewy.',
    details: ['Sun-dried', 'No preservatives', 'Source of iron', 'Naturally sweet'],
    inStock: true,
    weight: '400g',
  },
  {
    id: 'p12',
    name: 'Mixed Nut Trail',
    price: 18.90,
    originalPrice: 23.00,
    image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=600&q=80&auto=format&fit=crop',
    rating: 4.9,
    reviews: 298,
    badge: 'Best Seller',
    category: 'Nuts',
    description: 'Premium mixed nut trail blend — cashews, almonds, walnuts & pistachios.',
    details: ['4 premium nuts', 'No artificial flavor', 'High protein snack', 'Resealable bag'],
    inStock: true,
    weight: '450g',
  },
];

export const CATEGORIES = ['All', 'Dates', 'Berries', 'Nuts', 'Fruits'];

export const PROMO_CODES: Record<string, number> = {
  'DUZO15': 15,
  'WELCOME10': 10,
  'ORGANIC20': 20,
};
